name: .NET Framework 4.8

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 4.8.x

    - name: Restore dependencies
      run: dotnet restore Launcher.cn.csproj

    - name: Publish
      run: dotnet publish Launcher.cn.csproj

    - name: Archive Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Launcher
        path: Launcher.exe
