name: .NET Framework 4.8

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 4.8.1

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release Launcher.cn.csproj

    - name: Archive Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Launcher
        path: Launcher.exe
