name: .NET Framework 4.8

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install.NET Framework 4.8.1 Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-4.8.1

      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build Project
        run: |
          cd Launcher_GF
          dotnet build Launcher.cn.csproj

      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: Launcher
          path: Launcher.exe
