name: .NET Framework 4.8 Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/msbuild@v1
      with:
        msbuild-architecture: x86

    - name: Restore NuGet Packages
      run: nuget restore Launcher.cn.sln

    - name: Build Solution
      run: msbuild Launcher.cn.sln /p:Configuration=Release /p:Platform="Any CPU" /verbosity:minimal

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: |
          **/bin/Release/*
