name: MSBuild Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore --runtime win-x64  --output app --project Launcher.cn.csproj

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Launcher
          path: app\Launcher.exe
